name: shell_bash_bridge
description: "Shell-Bash-Bridge: learn and compare Bash and PowerShell commands."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  adaptive_icon_background: "#0B1220"
  adaptive_icon_foreground: assets/icons/app_icon_foreground.png

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
